CONFIG_STD_C17=y
CONFIG_COMPILER_WARNINGS_AS_ERRORS=y
# The SpO2 ratio and the pulse period are single-precision floats.
CONFIG_FPU=y

CONFIG_LOG=y

CONFIG_SENSOR=y
CONFIG_MAX30101_TRIGGER_GLOBAL_THREAD=y
